### ISSUE TITLE
Tp5.1

### ISSUE THREAD

**Issue by Trchh** [hellowzsg/fastadmin-thinkphp5.1#2]
一直在5.1和6中间纠结，看到有个升级了6.0版本的
最后还是想用5.1，所以想问一下
还在维护吗，这个项目。
后续有问题可以多交流指导一下吗

**Comment by hellowzsg** [comment]
本项目至少维护至2020年八月份，5.1是官方的LTS版本。
个人已经使用该项目在**实际开发中**
欢迎测试使用

**Comment by Trchh** [comment]
有QQ群么，或者加个QQ方便交流？

**Comment by Trchh** [comment]
QQ号1286865813，谢谢
