### ISSUE TITLE
执行完composer install后安装页面提示当前代码仅包含核心代码

### ISSUE THREAD

**Issue by Trchh** [hellowzsg/fastadmin-thinkphp5.1#3]
测试环境为nginx ，测试本地域名3.lo，指向3.lo/public，执行完composer install正常，
打开安装显示“显示当前代码仅包含核心代码，请前往官网下载完整包或资源包覆盖后再尝试安装，立即前往下载”

**Comment by hellowzsg** [comment]
`bower install`
应该是前端安装失败

**Comment by Trchh** [comment]
嗯，应该就是这个问题，我使用php think install 安装成功了 ，然后将原版里面的lib拷贝过来，正常运行了，建议将前端资源放到git内，以符合说明中的“Bower (可选)”

**Comment by Trchh** [comment]
嗯，应该就是这个问题，我使用php think install 安装成功了 ，然后将原版里面的lib拷贝过来，正常运行了，建议将前端资源放到git内，以符合说明中的“Bower (可选)”
